config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/words', to: 'words#index'
  get '/words/swears', to: 'words#swears'
end

app/models/Word.rb
class Word
  @words ||= JSON.parse(IO.readlines(File.join(Dir.pwd, '/app/assets/json_files/words.json'))[0])
  @swears ||= JSON.parse(IO.readlines(File.join(Dir.pwd, '/app/assets/json_files/swear.json'))[0])

  def self.random(limit = 10, swear: false)
    return (@words + @swears).sample(limit) if swear

    @words.sample(limit)
  end

  def self.swears(limit = 10)
    @swears.sample(limit)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

# Words controller
class WordsController < ApplicationController
  def index
    limit = (word_params[:limit] || 10).to_i
    swear = word_params[:swear] == 'true'

    # puts "#{limit}, #{swear}"
    @random_words = Word.random(limit, swear: swear)

    respond_to do |format|
      format.json { render json: @random_words }
      format.html
    end
  end

  def swears
    limit = (word_params[:limit] || 10).to_i
    @random_words = Word.swears(limit)

    respond_to do |format|
      format.json { render json: @random_words }
      format.html
    end
  end

  private

  def word_params
    params.permit(:limit, :swear, :format)
  end

  def params?
    params.key?(:limit) || params.key?(:swear)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/home/index.html.haml
%div.root
  %h1{ :style => "text-align: center;" } Welcome to Random Word API
  %div.docs
    %h3
      %li Documentation
    %div.line
      Send a GET request to
      %code /words?limit=10
      %br
      %li.params-info
        (change
        %code limit
        to get specific number of words)
    %div.line
      You can toggle on swear words as
      %code /words?swear=true
      %br
      %li.params-info
        (
        %code swear
        can be
        %code true
        or
        %code false
        )
      %div.line
        If you want only swear words:
        %br
        Send a GET request to
        %code /words/swears?limit=10
  %div.links
    %span= link_to raw("Words"), words_path, :title => 'Random words'
    %span= link_to raw("Swear words"), words_swears_path, :title => 'Random swear words'
  %div.credits
    %div.credits-title
      %hr.title-spacers
      %h5 Credits
      %hr.title-spacers
    %div
      All the words are gathered by 
      %a{ :href => "https://github.com/RazorSh4rk", :title => "RazorSh4rk" }
        RazorSh4rk
      %br
      Website built by me (
      %a{ :href => "https://github.com/nileshpandit009", :title => "Nilesh Pandit" }
        Nilesh Pandit
      )

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomWordApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_words.html.haml
%div.words
  - @random_words.each do |w|
    %h5= w

app/views/words/index.html.haml
%div
  %h3 Here are your random word(s)
  = render 'words', @random_words => @random_words

app/views/words/swears.html.haml
%div
  %h3 Here are your random swear word(s).
  = render 'words', @random_words => @random_words
  %h6{ :style => "color: var(--primary);" } I have one question. Why?